In [1]:
import torchvision as tv
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import numpy as np

train_ds = tv.datasets.MNIST(root='../datasets', train=True, transform=transforms.ToTensor())
train_dataloader = DataLoader(train_ds, batch_size=32, shuffle=True)  #60000

test_ds = tv.datasets.MNIST(root='../datasets', train=False, transform=transforms.ToTensor())
test_dataloader = DataLoader(test_ds, batch_size=32, shuffle=True)    #10000

In [2]:
train_itr = iter(train_dataloader)

In [3]:
x,y = train_itr.next()

In [4]:
x.shape

torch.Size([32, 1, 28, 28])

In [ ]:
y.shape

torch.Size([32])

In [5]:
y

tensor([9, 7, 6, 9, 6, 7, 2, 7, 2, 2, 0, 8, 1, 3, 7, 4, 0, 7, 1, 1, 9, 1, 5, 5,
        3, 2, 9, 4, 6, 2, 1, 5])

In [6]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )
input = streetlights[0] 
goal_prediction = walk_vs_stop[0]

for iteration in range(10):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]
 
        prediction = input.dot(weights)
 
        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error
 
        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
       #print("Prediction:" + str(prediction))
    print("Error:" + str(error_for_all_lights) + "\n")

Error:2.6561231104

Error:0.9628701776715985

Error:0.5509165866836797

Error:0.36445836852222424

Error:0.2516768662079895

Error:0.17797575048089034

Error:0.12864460733422164

Error:0.09511036950476208

Error:0.07194564247043436

Error:0.05564914990717743



In [7]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )

for iteration in range(10):
    error_for_all_lights = 0
    prediction = streetlights.dot(weights)
 
    error = (walk_vs_stop - prediction) ** 2
 
    delta = prediction-walk_vs_stop
    weights = weights - (alpha * (delta.dot(streetlights)))
    #print("Prediction:" + str(prediction))
    print("Error:" + str(np.sum(error)) + "\n")

Error:4.0652

Error:0.778488

Error:0.51437472

Error:0.3499687968

Error:0.24219861619199998

Error:0.17096470194047997

Error:0.12339449939973125

Error:0.09121487163943376

Error:0.06910050530544251

Error:0.053616479745658516



In [12]:
# immediate relationship 
# 这是一个非常有趣的ｅｘａｍｐｌｅ，实际上ｉｎｐｕｔ 与ｏｕｔｐｕｔ的关系是第一列第二列的ｘｏｒ，但是单层神经网络显然无法处理
# 最后的输出可以看到全部预测成了近0.5
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ]] )
walk_vs_stop = np.array( [ 1, 1, 0, 0 ] )

for iteration in range(100):
    error_for_all_lights = 0
    prediction = streetlights.dot(weights)
 
    error = (walk_vs_stop - prediction) ** 2
 
    delta = prediction-walk_vs_stop
    weights = weights - (alpha * (delta.dot(streetlights)))
    #print("Prediction:" + str(prediction))
    print("Error:" + str(np.sum(error)) + "\n")

Error:3.4967999999999995

Error:2.1234960000000003

Error:1.8460915999999998

Error:1.7246688615999999

Error:1.6341012726479995

Error:1.5566656332010398

Error:1.4889261876792328

Error:1.429461666622061

Error:1.3772337950464637

Error:1.3313582413690779

Error:1.291061877472662

Error:1.255666090666908

Error:1.2245748703063828

Error:1.1972647050609548

Error:1.1732757568715546

Error:1.1522041149468245

Error:1.1336949929353377

Error:1.1174367537868894

Error:1.1031556614955749

Error:1.0906112712696205

Error:1.0795923804498806

Error:1.0699134719541377

Error:1.061411590327079

Error:1.053943597767511

Error:1.0473837639083732

Error:1.0416216487495813

Error:1.036560243083548

Error:1.032114335091898

Error:1.0282090756024616

Error:1.0247787178425456

Error:1.0217655104640797

Error:1.0191187251981524

Error:1.0167938027642307

Error:1.0147516026511998

Error:1.0129577441368753

Error:1.0113820274493195

Error:1.0099979253230085

Error:1.0087821363884466

Error:1.00771419287

In [14]:
streetlights.dot(weights)   # 最后的输出可以看到全部预测成了近0.5


array([0.49979943, 0.4997989 , 0.49872025, 0.50087809])

In [17]:
# immediate relationship 
# 这是一个非常有趣的ｅｘａｍｐｌｅ，实际上ｉｎｐｕｔ 与ｏｕｔｐｕｔ的关系是第一列第二列的ｘｏｒ，但是单层神经网络显然无法处理
# 最后的输出可以看到全部预测成了近0.5
# 现在我们使用两层网络解决+relu note:*** non-linear is very very important***
import numpy as np
hidden_size = 8
layer0_weights = np.random.normal(0, 0.01, (3,hidden_size))
layer1_weights = np.random.normal(0, 0.01, (hidden_size,1))
alpha = 0.1

streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ]] )

walk_vs_stop = np.array( [[1, 1, 0, 0]] ).T

def relu(x):
    return np.where(x>=0, x, 0)

for iteration in range(350):
    error_for_all_lights = 0

    mid_prediction = streetlights.dot(layer0_weights)  # 4*3, 3*4 = 4*4
    mid_prediction = relu(mid_prediction) #if no non-linear, well, without it we can not get the result
    #mid_prediction = mid_prediction2    
    prediction = mid_prediction.dot(layer1_weights)    # 4*4, 4*1 = 4*1
 
    error = (walk_vs_stop - prediction) ** 2
 
    delta = prediction-walk_vs_stop   #  4*1
    
    layer1_weighted_delta = mid_prediction.T.dot(delta) # 4*4, 4*1 = 4*1
    layer0_weighted_delta = streetlights.T.dot(delta.dot(layer1_weights.T)*np.where(mid_prediction>0, 1, 0))      # 3*4
    
    layer1_weights = layer1_weights - alpha*layer1_weighted_delta
    layer0_weights = layer0_weights - alpha*layer0_weighted_delta
    
    #weights = weights - (alpha * (delta.dot(streetlights)))
    #print("Prediction:" + str(prediction))
    print(iteration, "Error:" + str(np.sum(error)) + "\n")

0 Error:2.000350256943338

1 Error:1.9987163915159107

2 Error:1.9970312580716842

3 Error:1.9948354317253674

4 Error:1.9916933942739288

5 Error:1.9869973192678132

6 Error:1.9798444282502417

7 Error:1.968927612813957

8 Error:1.95233483636063

9 Error:1.9273422665442674

10 Error:1.890253665073351

11 Error:1.8364692904384938

12 Error:1.76115454134699

13 Error:1.661053589368861

14 Error:1.5377718883909401

15 Error:1.4014668705241466

16 Error:1.2712175982112908

17 Error:1.1677389753654652

18 Error:1.1012609488687677

19 Error:1.066680148848964

20 Error:1.0513042166892306

21 Error:1.044623264764779

22 Error:1.0411561420812934

23 Error:1.0387625629278487

24 Error:1.0367358305261298

25 Error:1.0348689812261034

26 Error:1.033105760936031

27 Error:1.0314224629907431

28 Error:1.0298125868751145

29 Error:1.0282777216886203

30 Error:1.0268070864757548

31 Error:1.0254021056790377

32 Error:1.0240683915992643

33 Error:1.0227838829109257

34 Error:1.0215565686719354

35 Err

In [18]:
    mid_prediction = streetlights.dot(layer0_weights)  # 4*3, 3*4 = 4*4
    mid_prediction = relu(mid_prediction)
    prediction = mid_prediction.dot(layer1_weights)    # 4*4, 4*1 = 4*1
    print(prediction)  # yes we get it

[[ 0.9891687 ]
 [ 0.98915239]
 [-0.00101555]
 [ 0.00610189]]


In [ ]:
layer0_weights

array([[-0.00653096, -0.03911778,  0.02487826, -0.00116003],
       [ 0.00447833,  0.01646422, -0.00879874, -0.00079797],
       [-0.02122826,  0.24145203,  0.40569706,  0.52710568]])

In [ ]:
layer0_weights

array([[-5.97546950e-01,  3.95576539e-02,  8.07514749e-01,
         8.23080347e-02,  6.75414520e-02,  4.66503102e-01,
        -2.81706483e-03,  2.19393908e-03],
       [-5.97559079e-01,  3.19194709e-02,  8.02279767e-01,
         3.80081713e-01,  2.46819753e-01, -4.66508628e-01,
        -3.93792353e-03,  3.10115541e-02],
       [ 5.97548432e-01,  5.54821300e-02, -8.02277679e-01,
         6.04089819e-01,  3.82031871e-01, -5.52384589e-06,
        -6.34354782e-03,  2.00454109e-02]])

In [ ]:
layer1_weights

array([[ 1.09970485],
       [-0.01128219],
       [-1.78228359],
       [-0.01908169]])

In [ ]:
mid_prediction.shape

(4, 4)